static const char black[] = "#1e1d2d";
static const char gray2[] = "#282737"; // unfocused window border
static const char gray3[] = "#585767";
static const char gray4[] = "#282737";
static const char blue[] = "#96cdfb"; // focused window border
static const char green[] = "#abe9b3";
static const char red[] = "#f28fad";
static const char orange[] = "#f8bd96";
static const char yellow[] = "#fae3b0";
static const char pink[] = "#d5aeea";
static const char col_borderbar[] = "#1e1d2d"; // inner border
