static const char black[] = "#1E2122";
static const char gray2[] = "#282B2C"; // unfocused window border
static const char gray3[] = "#5D6061";
static const char gray4[] = "#282B2C";
static const char blue[] = "#6F8FAF"; // focused window border
static const char green[] = "#89B482";
static const char red[] = "#EC6B64";
static const char orange[] = "#D6B676";
static const char yellow[] = "#D1B171";
static const char pink[] = "#CC7F94";
static const char col_borderbar[] = "#1E2122"; // inner border
