static const char black[] = "#2e3440";
static const char gray2[] = "#3b4252"; // unfocused window border
static const char gray3[] = "#606672";
static const char gray4[] = "#6d8dad";
static const char blue[] = "#81a1c1"; // focused window border
static const char green[] = "#89b482";
static const char red[] = "#bf616a";
static const char orange[] = "#caaa6a";
static const char yellow[] = "#ebcb8b";
static const char pink[] = "#b48ead";
static const char col_borderbar[] = "#2e3440"; // inner border
