static const char black[] = "#1e222a";
static const char gray2[] = "#2e323a"; // unfocused window border
static const char gray3[] = "#545862";
static const char gray4[] = "#6d8dad";
static const char blue[] = "#89b4fa"; // focused window border
static const char green[] = "#7ec7a2";
static const char red[] = "#e06c75";
static const char orange[] = "#caaa6a";
static const char yellow[] = "#ebcb8b";
static const char pink[] = "#c678dd";
static const char col_borderbar[] = "#1e222a"; // inner border
