static const char black[] = "#1E222A";
static const char gray2[] = "#2E323A"; // unfocused window border
static const char gray3[] = "#545862";
static const char gray4[] = "#6D8DAD";
static const char blue[] = "#89b4fa"; // focused window border
static const char green[] = "#7EC7A2";
static const char red[] = "#E06C75";
static const char orange[] = "#CAAA6A";
static const char yellow[] = "#EBCB8B";
static const char pink[] = "#C678DD";
static const char col_borderbar[] = "#1E222A"; // inner border
