#!/bin/dash

# ---------------------------------------------- Colors ---------------------------------------------- #

black=#222526
green=#89B482
white=#C7B89D
grey=#2B2E2F
blue=#6F8FAF
red=#EC6B64
darkblue=#6080A0
