#!/bin/dash

# ---------------------------------------------- Colors ---------------------------------------------- #

black=#1E222A
green=#7ECA9C
white=#ABB2BF
grey=#282C34
blue=#7AA2F7
red=#D47D85
darkblue=#668EE3
